package com.example.pms.Controller;


import com.example.pms.Business.ApplicationService;
import com.example.pms.Business.InfoUpdate;
import com.example.pms.Model.Application;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

@RestController
@RequestMapping("/Application")
public class ApplicationController {

    @Autowired
    ApplicationService applicationService;

    @PutMapping("/{applicationId}/Status")
    ResponseEntity<String>UpdateApplication(@PathVariable Long applcationId, @RequestBody InfoUpdate info) {
        applicationService.updateApplicationStatus(applcationId, info.applicationStatus);
                return new ResponseEntity<>("Application Updated", HttpStatus.OK);
    }

    //Spring sees @RequestBody InfoUpdate info and hands the JSON off to Jackson
    //Jackson looks at each key in the JSON (here, applicationStatus) and tries to find a field with that exact name inside your InfoUpdate class
    //If InfoUpdate has a field literally named applicationStatus, Jackson calls its setter (setApplicationStatus(...), generated by Lombok) to fill it in

    @GetMapping("/Name")
     ResponseEntity<String>findApplicationStatus(@RequestBody InfoUpdate info) {
        String status = applicationService.findApplicationStatusBystudentName(info.studentName);
        return new ResponseEntity<>(status , HttpStatus.OK);
     }
     @GetMapping("/byId/{Id}")
     ResponseEntity<String>findApplicationStatus(@PathVariable Long applcationId) {
        String status = applicationService.findApplcationStatusByApplicationId(applcationId);
        return new ResponseEntity<>(status , HttpStatus.OK);

     }
     @GetMapping("/byName")
    ResponseEntity<Application>findApplication(@RequestBody InfoUpdate info) {
        Optional<Application> applicationObject = applicationService.findApplicationBystudentName(info.studentName);
        Application application = applicationObject.get();
        return new ResponseEntity<>(application, HttpStatus.OK);
     }
     @GetMapping("/{applicationId}")
    ResponseEntity<Application>findApplicationById(@PathVariable Long applicationId) {
         Optional<Application> applicationObject = applicationService.findApplicationById(applicationId);
         Application application = applicationObject.get();
         return new ResponseEntity<>(application, HttpStatus.OK);
     }
     @PostMapping()
    ResponseEntity<String>saveApplication(@RequestBody Application application) {
        String message = applicationService.SaveApplication(application);
        return new ResponseEntity<>(message,HttpStatus.OK);
     }
     @DeleteMapping("/{applicationId}")
    ResponseEntity<String>deleteApplication(@PathVariable Long applicationId) {
        String message = applicationService.DeleteApplication(applicationId);
        return new ResponseEntity<>(message,HttpStatus.OK);
    }
}
